### ISSUE TITLE
linking spoke vnets required??

### ISSUE THREAD

**Issue by swieder** [dmauser/azure-dns-private-resolver#1]
Is linking the spoke vnets required for the proper DNS resolution??  My understanding is that in this scenario, linking the spoke vnets would enable autoregistration of VMs into DNS zone but is not needed for DNS resolution with the DNS resolver.

**Comment by dmauser** [comment]
Good point, @swieder. You are right. Not required for name resolution (but recommended), but it is for auto-registration. For name resolution, you can also use other approaches; for example, you can change the VNET DNS settings to point to the DNS Private Resolver or Custom DNS server sitting in the Hub, and from there you can reach DNS Private Zone using 168.63.129.16.
